import NavBar from "@/components/Navibar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Adelaide Neighborhood Hub",
  description: "Generated by create next app",
};

export default function WithNavLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <NavBar />
      <main className="pt-24">{children}</main>
    </>
  );
}
